/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.presentacion;

import com.itson.dominio.Servicio;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import negocio.ILogica;
import negocio.LogicaNegocio;

/**
 *
 * @author alexasoto
 */
public class FrmConsulServicios extends javax.swing.JFrame {

    ILogica logica = new LogicaNegocio();
    
    
    /**
     * Creates new form FrmConsulServicios
     */
    public FrmConsulServicios() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.llenarTablaServ();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblServicio = new javax.swing.JLabel();
        btnRegresar = new javax.swing.JButton();
        scrlServicios = new javax.swing.JScrollPane();
        tblServicios = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setBackground(new java.awt.Color(255, 255, 255));
        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblServicio.setFont(new java.awt.Font("Kannada MN", 0, 20)); // NOI18N
        lblServicio.setText("Consultar servicios");
        pnlFondo.add(lblServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnRegresar.setBackground(new java.awt.Color(153, 204, 255));
        btnRegresar.setFont(new java.awt.Font("Kannada MN", 1, 14)); // NOI18N
        btnRegresar.setText("Regresar");
        btnRegresar.setFocusable(false);
        btnRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegresar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 100, -1));

        tblServicios.setFont(new java.awt.Font("Kannada MN", 0, 14)); // NOI18N
        tblServicios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Descripción", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrlServicios.setViewportView(tblServicios);

        pnlFondo.add(scrlServicios, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 280, 210));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmServicios frm = new FrmServicios();
        this.dispose();
        frm.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed


    public void llenarTablaServ() {
        List<Servicio> servicios = logica.recuperarServicios();
        DefaultTableModel modelo = (DefaultTableModel) this.tblServicios.getModel();
        modelo.setRowCount(0);
        for (Servicio servicio : servicios) {
            Object[] filaNueva = {servicio.getId(),servicio.getDescripcion() , servicio.getPrecio()};
            modelo.addRow(filaNueva);
        }
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblServicio;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JScrollPane scrlServicios;
    private javax.swing.JTable tblServicios;
    // End of variables declaration//GEN-END:variables
}
