/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.itson.presentacion;

import com.itson.dominio.Servicio;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocio.ILogica;
import negocio.LogicaNegocio;

/**
 *
 * @author Cristian
 */
public class FrmEditarServicio extends javax.swing.JFrame {

    ILogica logica = new LogicaNegocio();
    Servicio servicio1;
    Servicio servicio2;
    /**
     * Creates new form FrmEditarServicio
     */
    public FrmEditarServicio(Servicio servicio1) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.servicio1=servicio1;
        this.servicio2=servicio1;
        this.llenarTablaServ();
    }
    
     public void llenarTablaServ() {
        if (servicio2 != null) {
            this.txtDescripcion.setText(servicio2.getDescripcion());
            this.txtPrecio.setText(String.valueOf(servicio2.getPrecio()));
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblEditarServicio = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();
        lblDescripcion = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEditarServicio.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        lblEditarServicio.setText("Editar Servicio");
        pnlFondo.add(lblEditarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 320, -1, -1));

        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });
        pnlFondo.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, -1, -1));

        lblDescripcion.setText("Descripcion");
        pnlFondo.add(lblDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        lblPrecio.setText("Precio");
        pnlFondo.add(lblPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));
        pnlFondo.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 140, -1));
        pnlFondo.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 140, -1));

        getContentPane().add(pnlFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

                servicio1.setDescripcion(txtDescripcion.getText());
                String precioStr = txtPrecio.getText();
                float precio = Float.parseFloat(precioStr);
                servicio1.setPrecio(precio);
                if (logica.actualizarServicio(servicio1)) {
                    JOptionPane.showMessageDialog(this, "El servicio se actualizó correctamente");
                    this.setVisible(false);
                    FrmConsulServicios notas = new FrmConsulServicios();
                    notas.setVisible(true);
                    this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Ocurrio un error al editar el servicio");
            }

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        FrmServicios frm = new FrmServicios();
        this.dispose();
        frm.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblDescripcion;
    private javax.swing.JLabel lblEditarServicio;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
